apiVersion: apps/v1
kind: Deployment
metadata:
  name: inbound
  labels:
    app: inbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inbound
  template:
    metadata:
      labels:
        app: inbound
    spec:
      containers:
        - name: inbound
          image: username/inbound:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5