---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "inventory"
    labels: 
      app: "inventory"
  spec: 
    selector: 
      matchLabels: 
        app: "inventory"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "inventory"
      spec: 
        containers: 
          - 
            name: "inventory"
            image: "inventory"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "inventory"
    labels: 
      app: "inventory"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "inventory"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "inbound"
    labels: 
      app: "inbound"
  spec: 
    selector: 
      matchLabels: 
        app: "inbound"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "inbound"
      spec: 
        containers: 
          - 
            name: "inbound"
            image: "inbound"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "inbound"
    labels: 
      app: "inbound"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "inbound"
---
  apiVersion: "apps/v1"
  kind: "Deployment"
  metadata: 
    name: "outbound"
    labels: 
      app: "outbound"
  spec: 
    selector: 
      matchLabels: 
        app: "outbound"
    replicas: 1
    template: 
      metadata: 
        labels: 
          app: "outbound"
      spec: 
        containers: 
          - 
            name: "outbound"
            image: "outbound"
            ports: 
              - 
                containerPort: 8080
            readinessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 10
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 10
            livenessProbe: 
              httpGet: 
                path: "/actuator/health"
                port: 8080
              initialDelaySeconds: 120
              timeoutSeconds: 2
              periodSeconds: 5
              failureThreshold: 5
---
  apiVersion: "v1"
  kind: "Service"
  metadata: 
    name: "outbound"
    labels: 
      app: "outbound"
  spec: 
    ports: 
      - 
        port: 8080
        targetPort: 8080
    selector: 
      app: "outbound"
